[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
solana_twitter = "65DXLUP5PdaHYFDHBAicGyHnFbdW3vDK27uiYNfP3hu9"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/maksim/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
