[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
solana_twitter = "AthxBVtQahmg22ZBhSRkuCoZPHSWd2rbqsvMrgJxBCmP"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/Users/maksim/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
test_skip-validator = "anchor test --skip-local-validator"
